import { extendTailwindMerge } from "tailwind-merge";

const mergeClassnames = extendTailwindMerge({
  cacheSize: 0,
  extend: {
    theme: {
      spacing: [
        "space-0",
        "space-1",
        "space-10",
        "space-104",
        "space-112",
        "space-12",
        "space-120",
        "space-128",
        "space-136",
        "space-14",
        "space-144",
        "space-152",
        "space-16",
        "space-160",
        "space-18",
        "space-2",
        "space-20",
        "space-24",
        "space-28",
        "space-32",
        "space-36",
        "space-4",
        "space-40",
        "space-48",
        "space-56",
        "space-6",
        "space-64",
        "space-72",
        "space-8",
        "space-80",
        "space-88",
        "space-96",
        "space-neg12",
        "space-neg2",
        "space-neg4",
      ],
      borderRadius: [
        {
          moon: ["i-xs", "i-sm", "i-md", "s-xs", "s-sm", "s-md", "s-lg"],
        },
        "0",
        "2",
        "4",
        "6",
        "8",
        "12",
        "16",
        "20",
        "24",
        "32",
        "full",
      ],
      colors: [
        {
          moon: [
            "piccolo",
            "hit",
            "beerus",
            "goku",
            "gohan",
            "bulma",
            "trunks",
            "goten",
            "popo",
            "jiren",
            "heles",
            "zeno",
            { krillin: ["100", "60", "10"] },
            { chichi: ["100", "60", "10"] },
            { roshi: ["100", "60", "10"] },
            { dodoria: ["100", "60", "10"] },
            { cell: ["100", "60", "10"] },
            { raditz: ["100", "60", "10"] },
            { whis: ["100", "60", "10"] },
            { frieza: ["100", "60", "10"] },
            { nappa: ["100", "60", "10"] },
          ],
        },
        "active",
        "active-subtle",
        "brand",
        "brand-subtle",
        "caution",
        "caution-subtle",
        "discovery",
        "discovery-subtle",
        "force-dark",
        "force-light",
        "info",
        "info-subtle",
        "inverse",
        "link",
        "negative",
        "negative-subtle",
        "neutral",
        "neutral-subtle",
        "positive",
        "positive-subtle",
        "primary",
        "secondary",
      ],
      opacity: ["0", "20", "40", "60", "80", "100"],
      borderWidth: ["0", "1", "2", "4"],
      borderColor: [
        "active",
        "brand",
        "caution",
        "discovery",
        "force-dark",
        "force-light",
        "info",
        "inverse",
        "negative",
        "neutral",
        "positive",
        "primary",
        "secondary",
      ],
    },
    classGroups: {
      "font-size": [
        {
          moon: [
            "9",
            "9-caption",
            "10",
            "10-caption",
            "12",
            "14",
            "16",
            "18",
            "20",
            "24",
            "32",
            "40",
            "48",
            "56",
            "64",
            "72",
          ],
        },
        {
          body: ["100", "200", "300", "400", "500"],
        },
        {
          heading: ["100", "200", "300", "400", "500"],
        },
      ],
      shadow: [
        {
          moon: ["xs", "sm", "md", "lg", "xl"],
        },
        "100",
        "200",
        "300",
        "400",
        "500",
        "600",
      ],
    },
  },
});

export default mergeClassnames;
