import { extendTailwindMerge } from "tailwind-merge";

const mergeClassnames = extendTailwindMerge({
  cacheSize: 0,
  classGroups: {
    spacing: [
      "space-0",
      "space-1",
      "space-2",
      "space-4",
      "space-6",
      "space-8",
      "space-10",
      "space-12",
      "space-14",
      "space-16",
      "space-18",
      "space-20",
      "space-24",
      "space-28",
      "space-32",
      "space-36",
      "space-40",
      "space-48",
      "space-56",
      "space-64",
      "space-72",
      "space-80",
      "space-96",
      "space-104",
      "space-112",
      "space-120",
      "space-128",
      "space-136",
      "space-144",
      "space-152",
      "space-160",
    ],
    borderRadius: [
      {
        rounded: [
          "none",
          "full",
          {
            moon: ["i-xs", "i-sm", "i-md", "s-xs", "s-sm", "s-md", "s-lg"],
          },
          "0",
          "2",
          "4",
          "6",
          "8",
          "12",
          "16",
          "20",
          "24",
          "32",
        ],
      },
    ],
    fontSize: [
      {
        text: [
          {
            moon: [
              "9",
              "9-caption",
              "10",
              "10-caption",
              "12",
              "14",
              "16",
              "18",
              "20",
              "24",
              "32",
              "40",
              "48",
              "56",
              "64",
              "72",
            ],
          },
          {
            body: ["100", "200", "300", "400", "500"],
          },
          {
            heading: ["100", "200", "300", "400", "500"],
          },
        ],
      },
    ],
    color: [
      {
        text: [
          {
            moon: [
              "piccolo",
              "hit",
              "beerus",
              "goku",
              "gohan",
              "bulma",
              "trunks",
              "goten",
              "popo",
              "jiren",
              "heles",
              "zeno",
              { krillin: ["100", "60", "10"] },
              { chichi: ["100", "60", "10"] },
              { roshi: ["100", "60", "10"] },
              { dodoria: ["100", "60", "10"] },
              { cell: ["100", "60", "10"] },
              { raditz: ["100", "60", "10"] },
              { whis: ["100", "60", "10"] },
              { frieza: ["100", "60", "10"] },
              { nappa: ["100", "60", "10"] },
            ],
          },
          "primary",
          "secondary",
          "brand",
          "inverse",
          "positive",
          "caution",
          "negative",
          "info",
          "discovery",
          "active",
          "link",
          "force-light",
          "force-dark",
        ],
      },
    ],
    boxShadow: [
      {
        shadow: [
          {
            moon: ["xs", "sm", "md", "lg", "xl"],
          },
          "100",
          "200",
          "300",
          "400",
          "500",
          "600",
        ],
      },
    ],
  },
});

export default mergeClassnames;
