name: Build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build:
    name: "Build docs"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v5
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Corepack enable
        run: corepack enable
      - name: Use pnpm@8.15.6
        run: corepack prepare pnpm@8.15.6 --activate
      - name: Install dependencies
        run: pnpm i
      - name: Build packages
        run: pnpm run build
      - name: Build documentation
        run: pnpm run doc build
