name: Build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build:
    name: "Build & Lighthouse"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Corepack enable
        run: corepack enable
      - name: Use pnpm@latest
        run: corepack prepare pnpm@latest --activate
      - name: Install dependencies
        run: pnpm i
      - name: Build packages
        run: pnpm run build
      - name: Build documentation
        run: pnpm run doc build
      - name: Start documentation
        run: pnpm run doc start &
      - name: Lighthouse score
        run: pnpm exec lhci collect --url http://localhost:80
      - name: Lighthouse score upload
        run: pnpm exec lhci upload
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
