name: Changesets status
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    name: "Check if changeset is present in PR"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Corepack enable
        run: corepack enable
      - name: Use pnpm@latest
        run: corepack prepare pnpm@latest --activate
      - name: Install dependencies
        run: pnpm i
      - name: Check changeset status
        run: corepack pnpm changeset status --since origin/main
