name: Checks

# This action works with pull requests and pushes
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,jsx,tsx,md,mdx}

  spellcheck:
    name: Spellcheck

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@6f05386161564ebe24dcfa1513cde203230d1edc # v2.7.0

  changeset:
    name: Changeset

    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy

    steps:
      - uses: actions/checkout@v4
        with:
          # check out full history
          fetch-depth: 0
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - name: Corepack enable
        run: corepack enable
      - name: Use pnpm@8.15.6
        run: corepack prepare pnpm@8.15.6 --activate
      - name: Install dependencies
        run: pnpm i
      - name: Require changeset
        run: |
          # Checkout PR head commit instead of merge commit
          # See: https://github.com/atlassian/changesets/issues/517
          git config --global --add safe.directory /__w/moon-light/moon-light
          git checkout ${{ github.event.pull_request.head.sha }}
          pnpm changeset status --since=origin/main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
