name: Publish
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: "Build docs and publish npm packages"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"
      - name: Corepack enable
        run: corepack enable
      - name: Use pnpm@8.15.6
        run: corepack prepare pnpm@8.15.6 --activate
      - name: Install dependencies
        run: pnpm i
      - name: Build packages
        run: pnpm run build
      - name: Publish packages
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
